version: '3'
services:
  app:
    build: .
    ports:
      - "8081:8080"
      - "50000:50000"
    privileged: true
    volumes:
      #sudo chown -R 1000:1000 /volumes/jenkins_home then restart jenkins
      - ~/volumes/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker